generator:
  window_size: 0
  gamma: 0.5
  delta: 1.0
  chunk_size: 10
  mode: context
  transform_model_path: transform_model_cbert.pth
  embedding_model: c-bert
detector:
  window_size: 0
  gamma: 0.5
  delta: 1.0
  chunk_size: 10
  z_threshold: 0.0
  mode: context
  transform_model_path: transform_model_cbert.pth
  embedding_model: c-bert
